version: 2
updates:
- package-ecosystem: npm
  directory: "/rzp-ionic1-example"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: "/rzp-ionic2-example"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: "@ionic/storage"
    versions:
    - 2.3.1
    - 3.0.2
  - dependency-name: ionicons
    versions:
    - 5.4.0
    - 5.5.0
- package-ecosystem: npm
  directory: "/rzp-ionic3-example"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: "@ionic/storage"
    versions:
    - 2.3.1
    - 3.0.2
  - dependency-name: ionicons
    versions:
    - 5.4.0
    - 5.5.0
